name: CI

on: [pull_request]

jobs:
  Build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build project
        run: ./gradlew assemble
      - name: Run tests
        run: ./gradlew test
  Espresso:
    runs-on: macOS-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2.3.4
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Android Emulator test
        uses: ReactiveCircus/android-emulator-runner@v2.15.0
        with:
          api-level: 28
          disable-animations: true
          arch: x86_64
          profile: Nexus 6
          script: ./gradlew cAT
      - uses: actions/upload-artifact@v2.2.2
        if: ${{ always() }}
        with:
          name: Espresso-test-paho.mqtt-report
          path: ./**/build/reports/androidTests/connected
  Check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.1
      - name: Code checks
        run: ./gradlew check
      - name: Archive Lint report
        uses: actions/upload-artifact@v2.2.2
        if: ${{ always() }}
        with:
          name: Paho-Lint-report
          path: ./**/build/reports/lint-results.html
