name: Pull request

on: [ pull_request ]

jobs:
  Build:
    name: Build & Test
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      matrix:
        api: [ 28 ]
        abi: [ x86_64 ]
        tag: [ 'default' ]
#        include:
#          - api: 31
#            abi: x86_64
#            tag: 'google_apis'
#          - api: 30
#            abi: x86_64
#            tag: 'google_apis'
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Run tests
        run: ./gradlew test
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.4
      - name: Android Emulator test
        uses: malinskiy/action-android/emulator-run-cmd@release/0.1.4
        with:
          cmd: ./gradlew cAT --continue
          api: ${{ matrix.api }}
          tag: ${{ matrix.tag }}
          abi: ${{ matrix.abi }}
          cmdOptions: -noaudio -no-boot-anim -no-window
      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: MQ-Espresso-${{ matrix.api }}-${{ matrix.abi }}-report
          path: |
            ./**/build/reports/androidTests/connected
            ./**/build/outputs/androidTest-results/connected
            artifacts/logcat.log
      - name: Archive screenshots
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: MQ-Screenshots-${{ matrix.api }}-${{ matrix.abi }}
          path: screenshots/adb
  Check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.4
      - name: Kotlin code checks
        run: ./gradlew ktlintCheck
      - name: Code checks
        run: ./gradlew check
      - name: Archive Lint report
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: MQTT-Lint-report
          path: ./**/build/reports/lint-results.html
